### ISSUE TITLE
what is the package '.pds'

### ISSUE THREAD

**Issue by cellimnet** [trislaz/wsi_mil#3]
Hello:
         You have done a fantastic job! I'm eager to run your project, but in pkg/tile_wsi/sample.py, I'm not sure what the '.pds' module is about? Can you provide some clarification or guidance on it?
Thank you for your answering!

**Comment by trislaz** [comment]
Hello, 
Thanks for your interest! The code you're referring to was part of past experiments, where we attempted to implement non-uniform sampling through the packages pds and finiteDPP to enhance tiles diversity during training. 
The attempt was unfruitful and thus irrelevant to the current package. I've now removed the code. I appreciate you bringing this to my attention.
 Don't hesitate to reach out if you come across any other issues.

**Comment by cellimnet** [comment]
Thanks for your answer!
