### ISSUE TITLE
seek_best_tiles cannot work

### ISSUE THREAD

**Issue by cellimnet** [trislaz/wsi_mil#4]
Hello:
When running the seek_best_tiles.py, i get a error """assert self.store_score[o], "no tile found" AssertionError: no tile found""", i have followed the latest correction in "coquille" update for pkg/wsi_mil/visualizer/dissector.py and pkg/wsi_mil/visualizer/model_hooker.py, but i still get this error.
Thank you for your answering!

**Comment by trislaz** [comment]
Hello, 
Are you using --consensus ? I would recommend always use it.
I've modified the code to prevent this issue from reoccurring. However, encountering such an error might suggest that the models you're interpreting could be underfitted or overfitted. Please make sure the balanced metrics are good enough before placing complete faith in the interpretations!

**Comment by cellimnet** [comment]
Yes, i used --consensus, i'll check the performance of the models. Thanks for your answer!
