### ISSUE TITLE
HRD status of TCGA breast cancer

### ISSUE THREAD

**Issue by Luan-zb** [trislaz/wsi_mil#7]
Hello, I noticed in your article that the HRD status of TCGA breast cancer is obtained through the LST genomic signature. I wanted to ask how it is obtained and whether it varies for different subtypes? Could you please provide the label files? I would greatly appreciate it.

**Comment by trislaz** [comment]
Hello Luan, 
Actually we computed the scores internally. Other teams have done it and made the scores available (LST, but also LOH and TAI): here for example https://github.com/GerkeLab/TCGAhrd/blob/master/data/intermediateFIles/DDRscores.txt

I would recommend, now, to use the widely accepted HRD score which combines these three measures (this is the HRD score provided in the previous link).

**Comment by Luan-zb** [comment]
In the article by Knijnenburg et al. titled "Genomic and Molecular Landscape of DNA Damage Repair Deficiency across The Cancer Genome Atlas," they mentioned HRD scores along with other scores like LST, LOH, and TAI. However, they did not provide specific thresholds for classifying HRD and HRP labels. I've noticed that different researchers use various methods to determine these thresholds. Could you please confirm if you derived the HRD classification threshold directly from the calculated LOH score?

**Comment by trislaz** [comment]
We derived our binary classes HRD / HRP only from the LST score, with cut decided following "Ploidy and large-scale genomic instability consistently identify basal-like breast carcinomas with BRCA1/2 inactivation", Popova et al. i.e 15 or 20 LST score cutoff (not LOH).
